[package]
name = "skylite-compress"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dev-dependencies]
quickcheck = "^1"

[features]
default = ["lz77", "bit_prediction", "range_coding"]
lz77 = []
lz78 = []
bit_prediction = []
range_coding = []
