'((node . fizz-buzz)
  (subs .
    ((check-fizz .
       (  (set scratch.is-fizz #f)
        - (modify counter -3)
          (modify scratch.check-counter 1)
          (branch (>= counter 3) -)
          (branch (!= counter 0) +)
          (set scratch.is-fizz #t)
        + -
          (modify counter 3)
          (modify scratch.check-counter -1)
          (branch (> scratch.check-counter 0) -)))
     (check-buzz .
       (  (set scratch.is-buzz #f)
        - (modify counter -5)
          (modify scratch.check-counter 1)
          (branch (>= counter 5) -)
          (branch (!= counter 0) +)
          (set scratch.is-buzz #t)
        + -
          (modify counter 5)
          (modify scratch.check-counter -1)
          (branch (> scratch.check-counter 0) -)))
     (update-status .
       (  (set status "")
          (branch scratch.is-fizz ++)
          (branch (! scratch.is-buzz) +)
          (set status "buzz")
        + (return)
        ++ (branch scratch.is-buzz +)
          (set status "fizz")
          (return)
        + (set status "fizzbuzz")))))
  (script .
    (  (set counter 0)
       (set scratch.check-counter 0)
     - (modify counter 1)
       (call check-fizz)
       (call check-buzz)
       (call update-status)
       (wait 1)
       (branch stop +)
       (branch (>= counter 100) +)
       (jump -)
     + (return))))
